### ISSUE TITLE
NNFs in repository

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/un-orchestrator#108]
The NNFs **should not** be saved in tar.gz format.
Please remove them and add the sources to the repository. Then update the documentation by explaining that they must be packaged in a tar.gz

**Comment by ivanocerrato** [comment]
@rbrtbnfgl is this issue fixed?
If yes, please close it. Otherwise, it should be fixed :)

**Comment by ivanocerrato** [comment]
@rbrtbnfgl what is the status of this issue?

**Comment by rbrtbnfgl** [comment]
Done
