### ISSUE TITLE
update README_OpenWRT_ARM.md

### ISSUE THREAD

**Issue by cicciob92** [netgroup-polito/un-orchestrator#109]
update the guide for the compilation of the UN on ARM architecture by using Makefiles in 'un-orchestrator/contrib/OpenWrt/package' (use 'README_OpenWRT_MIPS.md' as example)

**Comment by ivanocerrato** [comment]
This issue is old. Alessandro in changing READMEs related to openwrt, as well as the structure of that part of repository,
