### ISSUE TITLE
Update resource description file

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/un-orchestrator#122]
The content of this file https://github.com/netgroup-polito/un-orchestrator/blob/master/orchestrator/config/universal-node-description.json should be updated according to the domain information library.

@farmanullahcs  I think you can put the file that you are using for your tests and that you showed me.

**Comment by farmanullahcs** [comment]
closed with [6eee](https://github.com/netgroup-polito/un-orchestrator/commit/6eee9334c90117f3de76459a0b549971e64e5e27) and [c4ee5](https://github.com/netgroup-polito/un-orchestrator/commit/c4ee5ba2019ae6db174fcce161c75779a4de48de)
