### ISSUE TITLE
Wrong comment?

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/un-orchestrator#132]
@piscoroma [here](https://github.com/netgroup-polito/un-orchestrator/blob/configuration_support/orchestrator/compute_controller/plugins/docker/scripts/pullAndRunNF.sh#L15) you say that it can be a relative path, but the example shows an absolute path.
Are you sure that it can be relative? In this case, relative with respect to what? Please, add an example.

**Comment by piscoroma** [comment]
You are right, it is an error. It has to be an absolute path. Now i will update it.

**Comment by piscoroma** [comment]
fixed
