### ISSUE TITLE
Netconf like rest API

### ISSUE THREAD

**Issue by ivanocerrato** [netgroup-polito/un-orchestrator#91]
Implement the rest API so that it works with commands that are netconf like. This means that the un-orch no longer has to calculate the diff of the graphs it receives, since each component of the graph has an associate command (e.g., create, remove, update?).

This requires changes both to the un-orch and to the virtualizer.

**Comment by ivanocerrato** [comment]
@frisso what do you think?

**Comment by frisso** [comment]
Probably we can stay with the current API for a while.

**Comment by ivanocerrato** [comment]
Ok
